### ISSUE TITLE
New release on pip

### ISSUE THREAD

**Issue by mgehre** [cosmin/stashy#109]
Thank you very much for stashy! It was easy to get started and has really helped us.

Could we please get new release on pip? The last one is from Feburary 2018,
and we would like to use newer features like the support for auth tokens that were introduced later.

Thank you!

**Comment by noahp** [comment]
FWIW I've been using this to bring in a more recent version of stashy (for the same reason, auth tokens :grinning: ), ex:
```
pip install git+https://github.com/cosmin/stashy.git#sha=2dd0582adb780aebba7c3182b0dd586c45167d0d
```
Similar syntax works in setup.py `install_requires` block:
```python
    install_requires=[
        "stashy @ git+https://github.com/cosmin/stashy.git#sha=2dd0582adb780aebba7c3182b0dd586c45167d0d",
    ],
```
Hope it helps!

**Comment by cosmin** [comment]
Done, 0.6 is now pushed.
