### ISSUE TITLE
New version release on pip

### ISSUE THREAD

**Issue by padraiglennon** [cosmin/stashy#150]
Hi.. 

I'm using this package quite a lot at the moment. Its great. Would it be possible to get a new release pushed to pypi to avail of at least this commit? https://github.com/cosmin/stashy/pull/47/commits/38cb1290739c09e838721b5fd43c2caa7b5ce9d4

Thanks in advance

**Comment by Victor-D** [comment]
Hello @cosmin and thanks for the work on this python lib.

@padraiglennon  is right, the 0.6 version in PyPi is from January 25, 2019.

Could you release the 0.7 version ? It would be nice to have the new features such as the pull request rebase() function, bug fix, etc.

**Comment by cosmin** [comment]
will fold this into #168 and work to cut a new release shortly
