### ISSUE TITLE
New pypi release?

### ISSUE THREAD

**Issue by wlupton** [cosmin/stashy#168]
There seem to be two versions of this repo in PyPi:

- stashy 0.6 - Jan 25, 2019 - Python API client for the Atlassian Bitbucket Server (formerly known as Stash) REST API
- stashy-mcherubinih 0.7.1 - Jul 26, 2020 - Python API client for the Atlassian Bitbucket Server (formerly known as Stash) REST API

The stashy-mcherubinih one is newer, but is still a few commits behind cosmin/stashy.

Is there any chance that a new PyPi release could be made from cosmin/stashy (after merging my PR #169 if you like!)? If this was done then perhaps @mcherubini would consider removing stashy-mcherubinih from PyPi?

Thanks.

----

This picture shows the two forks mentioned above, and also the BroadbandForum fork that has my PR.

<img width="728" alt="Screenshot 2021-02-24 at 13 02 05" src="https://user-images.githubusercontent.com/8874729/109004702-045dcb00-76a1-11eb-9abc-9aca85762d57.png">

**Comment by mcherubini** [comment]
Sorry for the delay @wlupton no problem from me to delete my forked library, i decided to fork the library and upload in the past because i needed the latest master changes, but its seems thats new changes from cosmin/stashy is not uploaded to PyPi anymore?

**Comment by mupdt** [comment]
@cosmin: I would also welcome a cut of v0.7. We are currently relying on a fork for #162 (which has already been merged).

**Comment by GPMueller** [comment]
@mcherubini since there has still been no response here and it seems a little unlikely we'll get an update any time soon (see also #150), I would actually like to ask you to upload your PyPI-package again 😀 some of the features since 0.6 would be nice to have without pulling in the sources

**Comment by cosmin** [comment]
I'm working on cutting a new release shortly. In general though I'd like to see if someone (ideally with some track record of making good contributions to the project) would like to volunteer to maintain this. It's hard for me to verify some of the pull requests and functionality as I no longer work with Stash / Bitbucket Server these days.

**Comment by cosmin** [comment]
0.7 has been released to PyPI

**Comment by harmathy** [comment]
Thanks @cosmin! Could you also make a release tag in github?
