### ISSUE TITLE
Running into issue when trying to make call for "/projects/{projectKey}/permissions/users   [GET]"

### ISSUE THREAD

**Issue by IIAXSISII** [cosmin/stashy#64]
Hi,

I am trying to make call for "/projects/{projectKey}/permissions/users" [GET], which is listed as implemented, but running into some issues. I have installed stashy in my local and I can make other calls as mentioned in example but, I am running into issues when trying to get the list of authenticated users at the project level. Can someone please let me know what is the correct call for this? I have tried following calls, but couldn't get it working. 

project = stash.projects['TEST_PROJECT'].permissions()
and 
project = stash.projects['TEST_PROJECT'].repos['test'].permissions()

Error for (project = stash.projects['TEST_PROJECT'].permissions())
$ ./user-audit.py 
Reteriving TEST_PROJECT project from stash!
Traceback (most recent call last):
  File "./user-audit.py", line 31, in <module>
    get_project()
  File "./user-audit.py", line 13, in get_project
    project = stash.projects['TEST_PROJECT'].permissions()
TypeError: 'ProjectPermissions' object is not callable

Error for (project = stash.projects['TEST_PROJECT'].repos['test'].permissions())
$ ./user-audit.py 
Reteriving TEST_PROJECT project from stash!
Traceback (most recent call last):
  File "./user-audit.py", line 31, in <module>
    get_project()
  File "./user-audit.py", line 13, in get_project
    project = stash.projects['TEST_PROJECT'].repos['test'].permissions()
TypeError: 'Permissions' object is not callable

**Comment by cosmin** [comment]
Try stash.projects['TEST_PROJECT'].repos['test'].permissions.list()

**Comment by IIAXSISII** [comment]
Still no luck for the call "/projects/{projectKey}/permissions/users [GET]" call. 

$ ./user-audit.py 
Reteriving TEST_PROJECT project from stash!
Traceback (most recent call last):
  File "./user-audit.py", line 31, in <module>
    get_project()
  File "./user-audit.py", line 13, in get_project
    project = stash.projects['TEST_PROJECT'].repos['test'].permissions.list()
AttributeError: 'Permissions' object has no attribute 'list'


$ ./user-audit.py 
Reteriving TEST_PROJECT project from stash!
Traceback (most recent call last):
  File "./user-audit.py", line 31, in <module>
    get_project()
  File "./user-audit.py", line 13, in get_project
    project = stash.projects['TEST_PROJECT'].permissions.list()
AttributeError: 'ProjectPermissions' object has no attribute 'list'

**Comment by tonytamsf** [comment]
@IIAXSISII please upload the 'user-audit.py script?

**Comment by cosmin** [comment]
Permissions have been updated to contain both users and group permissions so this api will now work differently. Closing this issue for now, please open a new issue if you are still having problems with 0.6
