### ISSUE TITLE
Branch-permissions for Bitbucket Server

### ISSUE THREAD

**Issue by schancel** [cosmin/stashy#74]
The API endpoints for the 1.0 API seem to have been removed in one of the Bitbucket Server releases. There are now a couple endpoints under the 2.0 version namespace.   Is a PR supporting the new endpoints for branch permissions welcome?

**Comment by tonytamsf** [comment]
Yes @schancel, I would love a PR

**Comment by mastindersingh** [comment]
I like to work on with you on this project and also check what is implemented and what need to be done.

**Comment by schancel** [comment]
This project got de-prioritized for me.  I had converted over the API to only use the new api.  That was a relatively simple change, but I wasn't sure based on the python wrappers being used as to how to implement fallback to the older API version.

**Comment by jonathanmorley** [comment]
Implemented in #121
