### ISSUE TITLE
pip install stashy fails for python 2.7

### ISSUE THREAD

**Issue by karthikkesavaraj** [cosmin/stashy#95]
Stashy 0.5 version does not install with python 2.7 
`pip install stashy`
'`Collecting stashy
  Downloading stashy-0.5.tar.gz
    Complete output from command python setup.py egg_info:
    error in stashy setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in enum34 ; python_version < '3.4' at  ; python_version < '3.4'`

Pip Version: 9.0.1
Python Version: 2.7.10

**Comment by v1-wizard** [comment]
You are use old version setuptools. It can't understand this type of syntax.

Please update your setuptools: `pip install --upgrade setuptools`

**Comment by karthikkesavaraj** [comment]
Yes. This worked. 
Thank you
